import AppKit
import XCTest
@testable import iLabelMac

final class CrossPlatformRichTextTests: XCTestCase {
    /// Generated by desktop/src/core/rtf.ts `serializeBase64RTF`.
    private let desktopRTF = "e1xydGYxXGFuc2lcYW5zaWNwZzEyNTJcdWMwe1xmb250dGJse1xmMFxmbmlsXGZjaGFyc2V0MCBBcmlhbDt9e1xmMVxmbmlsXGZjaGFyc2V0MCBDb3VyaWVyIE5ldzt9fXtcY29sb3J0Ymw7XHJlZDI1NVxncmVlbjBcYmx1ZTA7XHJlZDBcZ3JlZW4wXGJsdWUyNTU7XHJlZDBcZ3JlZW4xNTNcYmx1ZTA7fXtcKlxleHBhbmRlZGNvbG9ydGJsO1xjc2dlbmVyaWNyZ2JcYzEwMDAwMFxjMFxjMFxjMTAwMDAwO1xjc2dlbmVyaWNyZ2JcYzBcYzBcYzEwMDAwMFxjNTAwMDA7XGNzZ2VuZXJpY3JnYlxjMFxjNjAwMDBcYzBcYzEwMDAwMDt9e1xmMFxmczIwXGNmMSBBfXtcZjFcZnMzMlxiXGlcdWxcY2YyIFx1LTEwMTc5IFx1LTg3MDQgXHUtMTA5MTYgfXtcZjBcZnMyNFxjZjMgIEJvbGR9fQ=="

    func testDesktopRTFDecodesWithTextAndSelectionStyles() throws {
        let data = try XCTUnwrap(Data(base64Encoded: desktopRTF))
        let attributed = try NSAttributedString(
            data: data,
            options: [.documentType: NSAttributedString.DocumentType.rtf],
            documentAttributes: nil
        )

        XCTAssertEqual(attributed.string, "A😀한 Bold")

        let first = attributed.attributes(at: 0, effectiveRange: nil)
        let firstFont = try XCTUnwrap(first[.font] as? NSFont)
        XCTAssertEqual(firstFont.pointSize, 10, accuracy: 0.1)

        let styledIndex = (attributed.string as NSString).range(of: "😀한").location
        let styled = attributed.attributes(at: styledIndex, effectiveRange: nil)
        let styledFont = try XCTUnwrap(styled[.font] as? NSFont)
        let traits = NSFontManager.shared.traits(of: styledFont)
        XCTAssertEqual(styledFont.pointSize, 16, accuracy: 0.1)
        XCTAssertTrue(traits.contains(.boldFontMask))
        XCTAssertTrue(traits.contains(.italicFontMask))
        XCTAssertNotEqual((styled[.underlineStyle] as? Int) ?? 0, 0)

        let styledColor = try XCTUnwrap(styled[.foregroundColor] as? NSColor)
        XCTAssertEqual(styledColor.redComponent, 0, accuracy: 0.001)
        XCTAssertEqual(styledColor.greenComponent, 0, accuracy: 0.001)
        XCTAssertEqual(styledColor.blueComponent, 1, accuracy: 0.001)
        XCTAssertEqual(styledColor.alphaComponent, 0.5, accuracy: 0.01)

        let finalIndex = (attributed.string as NSString).range(of: "Bold").location
        let final = attributed.attributes(at: finalIndex, effectiveRange: nil)
        let finalFont = try XCTUnwrap(final[.font] as? NSFont)
        XCTAssertEqual(finalFont.pointSize, 12, accuracy: 0.1)
        let finalColor = try XCTUnwrap(final[.foregroundColor] as? NSColor)
        XCTAssertEqual(finalColor.greenComponent, 0.6, accuracy: 0.01)
    }
}
